name: "Lint shell scripts"
on:
  push:
    branches:
    - main
    paths:
    - '**.sh'
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: ludeeus/action-shellcheck@master
      env:
        SHELLCHECK_OPTS: -e SC1090,SC1091
