name: "Test build"
on:
  push:
    branches:
    - main
    paths:
    - '**.nix'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/checkout@v2.3.4
      with:
        path: 'nixos-generators'
        ref: 1.2.0
        repository: 'nix-community/nixos-generators'
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v8
      with:
        name: laptop
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: $GITHUB_WORKSPACE/tests/test_build.sh
      shell: bash
